defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/ScoreServer_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/ScoreServer_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/ScoreServer_production
    <<: *defaults